### ISSUE TITLE
Argument Parsing Error

### ISSUE THREAD

**Issue by OccamsXor** [p3nt4/RunDLL.Net#1]
Hi @p3nt4, 

I tried to execute the command below but it seems the class argument is empty. What could be the problem here? 

```
rundll32.exe .\Rundll.Net.dll,main C:\Users\john\Desktop\SharpSploit.dll  SharpSploit.Execution.Shell PowerShellExecute "ls C:\\" (bool)true (bool)false (bool)false
```
Error message:
```
######################   [runDll.Net]   ######################
[Assembly]   C:\Users\john\Desktop\SharpSploit.dll
[Class]
######################      Error      ######################
System.ArgumentException: String cannot have zero length.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at RunDLL.Net.Program.Main(String[] args)
```

**Comment by p3nt4** [comment]
Probably an extra space in between the assembly and class, need to add a fix for this situation in the code.

**Comment by OccamsXor** [comment]
Yes it was! Thank you @p3nt4  :D
